package com.jwd.controller.util;

public class Constants {
    public static final String
            PATH_TO_JSP = "WEB-INF/jsp/",
            JSP = ".jsp",
            LOGIN_ = "login",
            PASSWORD = "password",
            ROLE = "role",
            PAGE = "page",
            MESSAGE = "message",
            PASSWORD1 = "password1",
            PASSWORD2 = "password2",
            FIRST_NAME = "fName",
            LAST_NAME = "lName",
            PHONE = "phone",
            CITY = "city",
            STREET = "street",
            BUILDING = "building",
            APARTMENT = "apartment",
            BASKET = "basket",
            MENU = "menu",
            COMMAND = "command",
            DEFAULT_ = "default",
            CURRENT_PAGE = "currentPage",
            PAGE_LIMIT = "pageLimit",
            PAGEABLE = "pageable",
            MAIN = "main",
            ID = "id",
            ADDRESS = "addr",
            FIND_ADDRESS = "findAddr",
            PRODUCT = "product",
            USER = "user",
            FIND_USER = "findUser",
            SUM = "sum",
            PROD_ID = "productId",
            ORDER_ID = "orderId",
            NAME = "name",
            TYPE = "type",
            DESCRIPTION = "description",
            STATUS = "status",
            ADMIN_ID = "admin_id",
            PAGEABLE2 = "pageable2",
            PROFILE = "profile",
            PRICE = "price";
}
